### ISSUE TITLE
? appears in Favicon because window.FastMail is undefined

### ISSUE THREAD

**Issue by Flimm** [Rob-ot/Fastmail-Favicon-Unread-Count#2]
When I try this script out, I see a question mark in the favicon.

When I look in the console, I see this error:

```
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src"). Source: ;undefined.
window.FastMail is undefined
```
Funnily enough, when I type `window.FastMail` in the console, I do get an object.

**Comment by Rob-ot** [comment]
Hello, what are you using to run the script? Unfortunately some script runners like Scriptish don't handle CSP. Fastmail uses Content Security Policy for added security which prevents unauthorized JavaScript from running on the page.

Please let me know how you're running the script and try running it with Greasemonkey which handles CSP correctly.

**Comment by Rob-ot** [comment]
Okay, I'm also using Greasemonkey on Firefox desktop, I am actively using the script.

It looks like the script assumes `window.FastMail` is always defined so it may just need some extra checks. LMK if you find anything. I can make a version with extra checks for you to try if you'd like.
